"""Taxonomy verification UI — list every product type/section and show, on the actual
catalog page, the bounding box of the banner it was identified from. Built for verification:
click a section -> see exactly where on the page it came from.

Run from repo root:  python design-scratch/ui/taxonomy_app.py  -> http://localhost:8001
"""
from __future__ import annotations

import collections
import io
import json
import os
import sys

import fitz  # pymupdf
import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, Response
from pydantic import BaseModel

HERE = os.path.dirname(__file__)
BUILD = os.path.join(HERE, "..", "build")
sys.path.insert(0, BUILD)
import thin_pipeline as tp  # noqa: E402  (only for the SOURCES registry — no DB build)

_TAXDOC = json.load(io.open(os.path.join(HERE, "..", "taxonomy.json"), encoding="utf-8"))
# flatten the grouped taxonomy.json back to a section list (each section keeps its product_type)
TAX = [s for g in _TAXDOC["groups"] for t in g["types"] for s in t["sections"]]
SOURCES = tp.SOURCES
app = FastAPI(title="Taxonomy verifier")
_CACHE: dict = {}

# human review overlay — durable, committed, separate from the regenerated taxonomy.json
REVIEW_PATH = os.path.join(BUILD, "taxonomy_review.json")
OTHER_CATS = ["reference", "charts"]   # non-product buckets under "Other" (tooling is a product type)

# extracted product records (generated by build/extract.py); lazy-loaded per section in the UI
PRODUCTS_PATH = os.path.join(BUILD, "products.json")
# durable registry of problematic pages found during extraction (committed); shown under Other
ISSUES_PATH = os.path.join(BUILD, "extraction_issues.json")


def load_products():
    if os.path.exists(PRODUCTS_PATH):
        return json.load(io.open(PRODUCTS_PATH, encoding="utf-8")).get("products", [])
    return []


def load_issues():
    if os.path.exists(ISSUES_PATH):
        return json.load(io.open(ISSUES_PATH, encoding="utf-8")).get("issues", [])
    return []


def _issue_nodes():
    """Render each extraction issue as a review node placed under Other > Needs Review."""
    nodes = []
    for it in load_issues():
        pages = it.get("pages") or [it.get("page", 1)]
        nodes.append({
            "catalog": it["catalog"],
            "section": f"{it['section']} — p{','.join(str(x) for x in pages)}",
            "product_type": "Needs Review", "pages": [min(pages), max(pages)],
            "page": pages[0], "bbox": None, "approx_skus": 0, "brand": it.get("brand"),
            "n_products": 0, "review": None, "_issue": it,
        })
    return nodes


def _key(catalog, section):
    return f"{catalog}|{section}"


def load_review():
    if os.path.exists(REVIEW_PATH):
        return json.load(io.open(REVIEW_PATH, encoding="utf-8"))
    return {}


def save_review(data):
    with io.open(REVIEW_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)


@app.get("/api/taxonomy")
def api_taxonomy():
    """Hierarchical tree: Sections -> product_type -> sections (those not flagged), and
    Other -> Misc (sections a human flagged as 'not a product type')."""
    rev = load_review()
    pcount = collections.Counter((p["_source"], p["section"]) for p in load_products())
    secs = [{**s, "review": rev.get(_key(s["catalog"], s["section"])),
             "n_products": pcount.get((s["catalog"], s["section"]), 0)} for s in TAX]

    def cat(s):
        r = s.get("review")
        return r["status"] if r and r["status"] in OTHER_CATS else None

    products = [s for s in secs if not cat(s)]
    other_by = {c: [s for s in secs if cat(s) == c] for c in OTHER_CATS}
    by_type: dict = {}
    for s in products:
        by_type.setdefault(s["product_type"], []).append(s)
    sections_group = {"name": "Sections",
                      "types": [{"product_type": pt, "sections": by_type[pt]} for pt in sorted(by_type)]}
    other_group = {"name": "Other",
                   "types": [{"product_type": c.capitalize(), "sections": other_by[c]} for c in OTHER_CATS]}
    issue_nodes = _issue_nodes()
    other_group["types"].append({"product_type": "Needs Review", "sections": issue_nodes})
    open_issues = sum(1 for n in issue_nodes if (n["_issue"].get("status") or "open") != "resolved")
    return {"groups": [sections_group, other_group], "sources": SOURCES,
            "counts": {"products": len(products), "other": sum(len(v) for v in other_by.values()),
                       "issues": len(issue_nodes), "issues_open": open_issues}}


@app.get("/api/products")
def api_products(catalog: str, section: str):
    """Lazy-load the extracted products under one section (child nodes in the tree)."""
    prods = [p for p in load_products() if p["_source"] == catalog and p["section"] == section]
    return {"catalog": catalog, "section": section, "products": prods}


class Review(BaseModel):
    catalog: str
    section: str
    status: str          # "product" (clears the flag) | "not_product"
    note: str = ""


@app.post("/api/review")
def review(r: Review):
    data = load_review()
    k = _key(r.catalog, r.section)
    if r.status == "product":
        data.pop(k, None)                 # un-mark
    else:
        data[k] = {"status": r.status, "note": r.note, "by": "ui"}
    save_review(data)
    return {"ok": True, "review": data.get(k)}


@app.get("/page/{source}/{page}.png")
def page_png(source: str, page: int):
    key = (source, page)
    if key not in _CACHE:
        src = SOURCES.get(source)
        if not src:
            raise HTTPException(404, "unknown source")
        doc = fitz.open(src["pdf"])
        if not (1 <= page <= doc.page_count):
            raise HTTPException(404, "page out of range")
        _CACHE[key] = doc[page - 1].get_pixmap(matrix=fitz.Matrix(2, 2)).tobytes("png")
    return Response(_CACHE[key], media_type="image/png")


@app.get("/", response_class=HTMLResponse)
def index():
    return FileResponse(os.path.join(HERE, "static", "taxonomy.html"))


if __name__ == "__main__":
    print(f"Taxonomy verifier: {len(TAX)} sections -> http://localhost:8001")
    uvicorn.run(app, host="127.0.0.1", port=8001)
